site_name: NFDI4Culture Data Stories
site_description: Telling stories with data on material and immaterial cultural heritage
site_author: NFDI4Culture

repo_url: https://gitlab.rlp.net/adwmainz/nfdi4culture/knowledge-graph/shmarql/datastories

theme:
  name: nfdi4culture
  locale: en
  include_search_page: true
  static_templates:
    - 404.html

extra_javascript:
  - overrides/assets/javascripts/jquery.dataTables.min.js
  - overrides/assets/vendor/sgvizler2.js
  - overrides/assets/javascripts/extra.js
  - overrides/assets/vendor/plotly-3.0.1.min.js
  - overrides/assets/vendor/lib/leaflet/leaflet.js
  - overrides/assets/javascripts/duckdb-wasm-loader.js
  - overrides/assets/javascripts/baroque-viz.js
  - overrides/assets/javascripts/dashboard-overview-micro.js

extra_css:
  - overrides/assets/stylesheets/jquery.dataTables.min.css
  - overrides/assets/vendor/lib/leaflet/leaflet.css
  - overrides/assets/stylesheets/extra.css
  - overrides/assets/stylesheets/dashboard-overview-micro.css



plugins:
  - search
  - awesome-nav

markdown_extensions:
  - abbr
  - attr_list
  - footnotes
  - md_in_html
  - shmarql
  - toc:
      permalink: false
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.blocks.admonition
  - pymdownx.blocks.caption
  - pymdownx.blocks.definition
  - pymdownx.blocks.details
  - pymdownx.blocks.html
  - pymdownx.blocks.tab
  - pymdownx.caret
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path:
        - docs/story/E6263/
        - docs/story/E6477/
        - docs/story/CbDD/
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
